trainer: energy

dataset:
  - src: data/is2re/10k/train/data.lmdb
    normalize_labels: True
    target_mean: -0.14427930188676977
    target_std: 0.07261932711608407
  - src: data/is2re/all/val_id/data.lmdb

logger: tensorboard

task:
  dataset: single_point_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy
